### ISSUE TITLE
forecast.io optional parameters

### ISSUE THREAD

**Issue by christopherjanzen** [nickswalker/forecast.io-dashboard-widget#1]
I was wondering if you could add support for the optional parameters from forecast.io
For example, I live in Canada so I much prefer using celsius and km/h. I tried adding the proper code to the iframe html file but it didn't seem to work.
optional parameters can be found here: http://blog.forecast.io/forecast-embeds/

**Comment by nickswalker** [comment]
I've spent some time looking at adding this but my I've been hampered by the lack of a functioning build of Dashcode for Mavericks. Even with the work arounds to get it to launch I've been getting unexpected and unpredictable behavior. While I see what I can do, you can append any additional parameters to the embed manually by simply adding them to the end of the Location Name field like this:
![screen shot 2014-01-01 at 7 05 21 pm](https://f.cloud.github.com/assets/924295/1830518/fd563d36-7349-11e3-9e11-a184f709b787.png)

This isn't a real solution naturally, but it will work in the meantime.

**Comment by christopherjanzen** [comment]
I would imagine that would be added to main.html with my limited understanding of widgets but this didn't seem to work. The widget itself seems to work great on my install of 10.9.

**Comment by christopherjanzen** [comment]
Never mind. I see that you meant the actual location field within the widget. This does work as a workaround but I'm fine with that!

**Comment by nickswalker** [comment]
I've added a units control in v1.1. Thanks for your patience!
![screen shot 2014-03-10 at 3 31 33 pm](https://f.cloud.github.com/assets/924295/2378780/172e77ae-a893-11e3-9201-25ed5fcd8a6d.png)

**Comment by christopherjanzen** [comment]
Looks good, nice work!
